### PR TITLE
Remove 'starlight' reference

### PR DESCRIPTION
**Pull request by subnut**

### CODE REVIEW

**Comment by subnut** [comment]
@mox-mox I was thinking, should we mention in the README about the function `localsearch#Toggle()` that is made public?
It would be useful for ...  if someone wants to enable localsearch by default in `init.vim`

**Comment by subnut** [comment]
@mox-mox What happened? No reply?

**Comment by mox-mox** [comment]
I'm not sure, why somebody would want to enable localsearch by default, but I'll merge a PR that mentions it. Sorry for the lengthy reply time...

**Comment by subnut** [comment]
> I'm not sure, why somebody would want to enable localsearch by default

I do! :smile: 
I have `localsearch#Enable()` in my `.vimrc`
I find it **very** helpful to have my last search local to the window. Thanks for this amazing plugin.

In fact, I even went as far as modifying the Localsearch extension in airline to allow a setting (`let g:airline#extensions#localsearch#inverted = 1`) to show the extension only when localsearch is _disabled_. It shows `GS` (denoting GlobalSearch) instead of `LS`

**Comment by mox-mox** [comment]
Sounds nice. Are you going to upstream your changes to the airline extension?

**Comment by subnut** [comment]
Already did 😄
vim-airline/vim-airline#2240

**Comment by mox-mox** [comment]
Uh, nice!

**Pull request merged**
